strand = input("Enter Desired DNA Strand: ")
S = strand.upper()
St = S.replace("T", "t")
SA = St.replace("A", "T")
AT_S = SA.replace("t", "A")
Sc = AT_S.replace("C", "c")
SG = Sc.replace("G", "C")
Complement_S = SG.replace("c", "G")
print(Complement_S)
