DNA = input("Enter DNA strand: ").upper().strip()
DNA_A = DNA.replace('A', '')
DNA_T = DNA_A.replace('T', '')
DNA_G = DNA_T.replace('G', '')
strand = DNA_G.replace('C', '')
if bool(strand) is False:
    St = DNA.replace("T", "t")
    SA = St.replace("A", "T")
    AT_S = SA.replace("t", "A")
    Sc = AT_S.replace("C", "c")
    SG = Sc.replace("G", "C")
    Complement_S = SG.replace("c", "G")
    print(Complement_S)
else:
    print("This is not a valid DNA strand")
